// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgYrllc-Ie8RMF6QgUfrHSa_TRQn6u0hY',
    appId: '1:284235510726:web:012a190e0d585b65ff78c7',
    messagingSenderId: '284235510726',
    projectId: 'rickandmorty-co',
    authDomain: 'rickandmorty-co.firebaseapp.com',
    storageBucket: 'rickandmorty-co.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxXH180DECCVIRFKrYdXRJKk8auGrYh0',
    appId: '1:284235510726:android:bb208dc4b020c936ff78c7',
    messagingSenderId: '284235510726',
    projectId: 'rickandmorty-co',
    storageBucket: 'rickandmorty-co.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUQ0VKbYEVnMn0MFDS5pYKriHlrEDuH_Y',
    appId: '1:284235510726:ios:de8a5366646308e5ff78c7',
    messagingSenderId: '284235510726',
    projectId: 'rickandmorty-co',
    storageBucket: 'rickandmorty-co.appspot.com',
    iosBundleId: 'com.example.rickandmorty',
  );
}
